version: '3.9'

services:

  administrative-app-api:
    extends:
      file: ./docker/docker-compose.base.yml
      service: administrative-app-api-base
    build: 
      context: .
      dockerfile: dockerfile
    environment:
      - DATABASE_URL=jdbc:mysql://administrative-app-db:${MYSQL_PORT}/${MYSQL_DATABASE}
    depends_on:
      - administrative-app-db
    networks:
      - backend
    env_file:
      - ./.env

  administrative-app-db:
    extends:
      file: ./docker/docker-compose.base.yml
      service: administrative-app-db-base
    volumes:
      - administrative-app-db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  administrative-app-db-data:

networks:
  backend:
    driver: bridge
