version: '3.9'

services:

  administrative-app-api-base:
    image: ${DOCKER_SERVER_IMAGE_NAME}:${DOCKER_SERVER_IMAGE_VERSION}  
    container_name: ${DOCKER_SERVER_CONTAINER_NAME}
    ports:
      - ${SERVER_PORT}:8080
  
  administrative-app-db-base:
    image: mysql:8.4.0
    container_name: ${DOCKER_DATABASE_CONTAINER_NAME}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}