version: '3.9'

services:
  administrative-app-api:
    build: 
      context: ./.devcontainer/
      args:
        ROOT_USER_PASSWORD: ${ROOT_USER_PASSWORD}
      dockerfile: dockerfile.devcontainer
    volumes:
      - ./:/workspace/administrative-app
    working_dir: /workspace/administrative-app
    env_file:
      - ./.devcontainer/.env.dev
    # entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 

